apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repository
      description: Git repository URL
    - name: revision
      description: Git branch
      default: main
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone -b $(params.revision) $(params.repository) /workspace/shared-workspace
    - name: deploy
      image: alpine:3.19
      workingDir: /workspace/shared-workspace
      script: |
        #!/bin/sh
        echo "This is a deploy step..."
        echo "Deploying commit from branch $(params.revision)"
