apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repository
      description: Git repository URL
    - name: revision
      description: Git branch
      default: main
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        echo "Cleaning workspace..."
        rm -rf /workspace/source/*
        echo "Cloning $(params.repository) branch $(params.revision)"
        git clone -b $(params.revision) $(params.repository) /workspace/source
    - name: lint
      image: python:3.11
      workingDir: $(workspaces.shared-workspace.path)/repo
      script: |
        #!/bin/sh
        set -e
        pip install pylint
        # Run pylint only on the testcases folder
        pylint $(find testcases/ -type f -name "*.py") || true
