apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lint-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repository
    - name: revision
  tasks:
    - name: run-lint
      taskRef:
        name: lint-task
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
