apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-template
spec:
  params:
    - name: repository-url
    - name: revision
    - name: ref
    - name: event-type
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-pipeline-run-
      spec:
        pipelineRef:
          name: ci-pipeline
        params:
          - name: repository-url
            value: $(tt.params.repository-url)
          - name: revision
            value: $(tt.params.revision)
          - name: ref
            value: $(tt.params.ref)
          - name: event-type
            value: $(tt.params.event-type)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                name: ci-ws
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ci-binding-push
spec:
  params:
    - name: repository-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.repository.default_branch)
    - name: ref
      value: $(body.ref)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ci-binding-pr
spec:
  params:
    - name: repository-url
      value: $(body.pull_request.head.repo.clone_url)
    - name: revision
      value: $(body.pull_request.head.ref)
    - name: ref
      value: $(body.pull_request.base.ref)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ci-listener
spec:
  serviceAccountName: pipeline
  triggers:
    # === Deploy: PUSH a main ===
    - name: on-push-main
      bindings:
        - ref: ci-binding-push
        # binding embebido: fija el tipo de evento
        - name: event-type
          value: push
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
          params:
            - name: eventTypes
              value: ["push"]
        - ref:
            name: cel
            kind: ClusterInterceptor
          params:
            - name: filter
              value: >-
                header.match('X-GitHub-Event','push') &&
                body.ref == 'refs/heads/main' &&
                !body.deleted
      template:
        ref: ci-template

    # === Lint: PR opened/synchronize/reopened ===
    - name: on-pr-lint
      bindings:
        - ref: ci-binding-pr
        # binding embebido: fija el tipo de evento
        - name: event-type
          value: pull_request
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
          params:
            - name: eventTypes
              value: ["pull_request"]
        - ref:
            name: cel
            kind: ClusterInterceptor
          params:
            - name: filter
              value: >-
                header.match('X-GitHub-Event','pull_request') &&
                (body.action in ['opened','synchronize','reopened'])
      template:
        ref: ci-template
