apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: lint-template
spec:
  params:
    - name: repository
      description: Git repository URL
    - name: revision
      description: Git branch
      default: main
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: lint-pipeline-run-
      spec:
        pipelineRef:
          name: lint-pipeline
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                name: lint-pvc
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.revision)
