---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: lint-template
spec:
  params:
    - name: repository
      description: Git repository URL
    - name: branch
      description: Git branch
      default: main
    - name: event-type
      description: Type of event (push or pull_request)
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: lint-pipeline-run-
      spec:
        pipelineRef:
          name: lint-pipeline
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                name: lint-pvc
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: event-type
            value: $(params.event-type)

---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: lint-binding
spec:
  params:
    - name: repository
      value: "https://github.com/Daniel-Ruiz-Gtz/Tekton-tests"
    - name: branch
      value: "$(body.ref)"             # Ej: refs/heads/main
    - name: event-type
      value: "$(header.X-GitHub-Event)"   # Ej: push o pull_request

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: lint-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - binding:
        name: lint-binding
      template:
        name: lint-template
