apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: lint-template
spec:
  params:
    - name: repository
    - name: revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: lint-pipeline-run-
      spec:
        pipelineRef:
          name: lint-pipeline
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                name: lint-pvc
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: repository
            value: $(params.repository)
          - name: revision
            value: $(params.revision)

---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: deploy-template
spec:
  params:
    - name: repository
    - name: revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: deploy-pipeline-run-
      spec:
        pipelineRef:
          name: deploy-pipeline
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                name: deploy-pvc
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: repository
            value: $(params.repository)
          - name: revision
            value: $(params.revision)

---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: lint-binding
spec:
  params:
    - name: repository
      value: "https://github.com/Daniel-Ruiz-Gtz/Tekton-tests"
    - name: revision
      value: "main"

---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: deploy-binding
spec:
  params:
    - name: repository
      value: "https://github.com/Daniel-Ruiz-Gtz/Tekton-tests"
    - name: revision
      value: "main"

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ci-listener
spec:
  triggers:
    - name: pr-lint
      bindings:
        - ref: lint-binding
      template:
        ref: lint-template
      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value:
                - pull_request
    - name: push-deploy
      bindings:
        - ref: deploy-binding
      template:
        ref: deploy-template
      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value:
                - push
