apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-template
spec:
  params:
    - name: repository-url
    - name: revision
    - name: ref
    - name: event-type
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-pipeline-run-
      spec:
        pipelineRef:
          name: ci-pipeline
        params:
          - name: repository-url
            value: $(tt.params.repository-url)
          - name: revision
            value: $(tt.params.revision)
          - name: ref
            value: $(tt.params.ref)
          - name: event-type
            value: $(tt.params.event-type)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                name: ci-ws
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ci-binding-push
spec:
  params:
    - name: repository-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.repository.default_branch)
    - name: ref
      value: $(body.ref)
    - name: event-type
      value: "$(header['x-github-event'])"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ci-binding-pr
spec:
  params:
    - name: repository-url
      value: $(body.pull_request.head.repo.clone_url)
    - name: revision
      value: $(body.pull_request.head.ref)
    - name: ref
      value: $(body.pull_request.base.ref)
    - name: event-type
      value: "$(header['x-github-event'])"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ci-listener
spec:
  triggers:
    - name: on-push
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "header['x-github-event'] == 'push'"
      bindings:
        - ref: ci-binding-push
      template:
        ref: ci-template
    - name: on-pr
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "header['x-github-event'] == 'pull_request' && (body.action == 'opened' || body.action == 'synchronize' || body.action == 'reopened')"
      bindings:
        - ref: ci-binding-pr
      template:
        ref: ci-template
