apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: simple-template
spec:
  params:
    - name: repository
      description: Git repository URL
    - name: revision
      description: Git branch
      default: main
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: simple-pipeline-run-
      spec:
        pipelineRef:
          name: simple-pipeline
        params:
          - name: repository
            value: $(params.repository)
          - name: revision
            value: $(params.revision)

---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: simple-binding
spec:
  params:
    - name: repository
      value: "https://github.com/Daniel-Ruiz-Gtz/Tekton-tests"
    - name: revision
      value: "main"

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ExteGit Listener
spec:
  triggers:
    - binding:
        name: simple-binding
      template:
        name: simple-template
