apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lint-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: lint
      taskRef:
        name: lint-task
      workspaces:
        - name: source
          workspace: shared-workspace
