---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lint-pipeline
spec:
  params:
    - name: repository
    - name: branch
    - name: event-type
  workspaces:
    - name: shared-workspace
  tasks:
    - name: run-lint
      taskRef:
        name: lint-task
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      when:
        - input: "$(params.event-type)"
          operator: In
          values: ["pull_request"]

    - name: run-deploy
      taskRef:
        name: deploy-task
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      when:
        - input: "$(params.event-type)"
          operator: In
          values: ["push"]
        - input: "$(params.branch)"
          operator: In
          values: ["main"]
