apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  params:
    - name: repository-url
      type: string
      description: The URL of the Git repository to clone.
    - name: revision
      type: string
      description: The branch or tag to checkout.
    - name: ref
      type: string
      description: The git ref that triggered the pipeline.
    - name: event-type
      type: string
      description: The type of event that triggered the pipeline.
  workspaces:
    - name: shared-workspace

  tasks:
    - name: git-clone
      description: Clone the Git repository.
      taskRef:
        name: git-clone-task
      params:
        - name: repository-url
          value: $(params.repository-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: lint
      description: Run linting on the source code.
      taskRef:
        name: lint-task
      runAfter: 
        - git-clone
      when:
        - input: $(params.event-type)
          operator: in
          values: ["pull_request"]
      params:
        - name: repository-url
          value: $(params.repository-url)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: deploy
      description: Deploy the application.
      taskRef:
        name: deploy-task
      runAfter:
        - lint
      when:
        - input: $(params.event-type)
          operator: in
          values: ["push"]
        - input: $(params.ref)
          operator: in
          values: ["refs/heads/main"]
      workspaces:
        - name: output
          workspace: shared-workspace
