apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  params:
    - name: repository-url
    - name: revision
    - name: ref
    - name: event-type
    - name: action
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: repository-url
          value: $(params.repository-url)
        - name: revision
          value: $(params.revision)
      when:
        - input: "$(params.event-type)"
          operator: in
          values: ["pull_request"]

    - name: lint
      taskRef:
        name: lint
      runAfter: ["clone"]
      when:
        - input: "$(params.event-type)"
          operator: in
          values: ["pull_request"]

    - name: deploy
      taskRef:
        name: deploy
      when:
        - input: "$(params.event-type)"
          operator: in
          values: ["push"]
        - input: "$(params.ref)"
          operator: in
          values: ["refs/heads/main"]
