apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lint-pipeline
spec:
  params:
    - name: repository
      description: Git repository URL
    - name: revision
      description: Git branch
      default: main
  workspaces:
    - name: shared-workspace
  tasks:
    - name: lint
      taskRef:
        name: lint-task
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)