apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: repository
      description: Git repository URL
    - name: revision
      description: Git branch
      default: main
  tasks:
    - name: clone-and-echo
      taskRef:
        name: echo-task
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
