apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  params:
    - name: repository-url
      type: string
    - name: ref
      type: string
    - name: event-type
      type: string
    - name: action
      type: string
  workspaces:
    - name: shared-workspace

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone-task
      params:
        - name: url
          value: $(params.repository-url)
        - name: rev
          value: $(params.ref)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: lint
      runAfter: [ git-clone ]
      when:
        - input: "$(params.event-type)"
          operator: in
          values: ["pull_request"]
        - input: "$(params.action)"
          operator: in
          values: ["opened","synchronize","reopened"]
      taskRef:
        name: lint-task
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: deploy
      runAfter: [ git-clone ]
      when:
        - input: "$(params.event-type)"
          operator: in
          values: ["push"]
        - input: "$(params.ref)"
          operator: in
          values: ["refs/heads/main"]
      taskRef:
        name: deploy-task
      workspaces:
        - name: source
          workspace: shared-workspace
