apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  params:
    - name: repository-url
      type: string
    - name: revision
      type: string
    - name: ref
      type: string
    - name: event-type
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: show-params
      taskRef: { name: show-params-task }
      params:
        - { name: repository-url, value: $(params.repository-url) }
        - { name: revision,       value: $(params.revision) }
        - { name: ref,            value: $(params.ref) }
        - { name: event-type,     value: $(params.event-type) }

    - name: git-clone
      runAfter: [show-params]
      when:
        - { input: $(params.event-type), operator: in, values: ["pull_request"] }
      taskRef: { name: git-clone-task }
      params:
        - { name: url, value: $(params.repository-url) }
        - { name: rev, value: $(params.revision) }
      workspaces:
        - { name: output, workspace: shared-workspace }

    - name: lint
      runAfter: [git-clone]
      when:
        - { input: $(params.event-type), operator: in, values: ["pull_request"] }
      taskRef: { name: lint-task }
      params:
        - { name: repository-url, value: $(params.repository-url) }
      workspaces:
        - { name: source, workspace: shared-workspace }

    - name: deploy
      runAfter: [show-params]
      when:
        - { input: $(params.event-type), operator: in, values: ["push"] }
        - { input: $(params.ref),        operator: in, values: ["refs/heads/main"] }
      taskRef: { name: deploy-task }
      workspaces:
        - { name: source, workspace: shared-workspace }
