---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: url
      type: string
    - name: rev
      type: string
  workspaces:
    - name: output
  steps:
    - name: echo-clone
      image: alpine:3.19
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        echo ">>> [GIT CLONE TASK]"
        echo "Cloning repo from: $(params.url)"
        echo "Revision: $(params.rev)"
        echo "Files would be placed into $(workspaces.output.path)/source"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  workspaces:
    - name: source
  steps:
    - name: echo-lint
      image: alpine:3.19
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo ">>> [LINT TASK]"
        echo "Running pylint (dummy) in $(workspaces.source.path)/source/testcases"
        echo "This is where the linting would happen."

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: source
  steps:
    - name: echo-deploy
      image: alpine:3.19
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo ">>> [DEPLOY TASK]"
        echo "This is where the deploy process would run for branch main."
