apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: repository-url
    - name: revision
  steps:
    - name: echo
      image: alpine:3.18
      script: |
        echo "[GIT CLONE] Repo: $(params.repository-url)"
        echo "[GIT CLONE] Branch/Rev: $(params.revision)"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  steps:
    - name: echo
      image: alpine:3.18
      script: |
        echo "[LINT] Running pylint inside testcases/ folder..."

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  steps:
    - name: echo
      image: alpine:3.18
      script: |
        echo "[DEPLOY] Deploy triggered by push to main"
