apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-params-task
spec:
  params:
    - name: repository-url
    - name: revision
    - name: ref
    - name: event-type
  steps:
    - name: echo-params
      image: alpine:3.19
      script: |
        #!/bin/sh
        echo ">>> [SHOW PARAMS]"
        echo "repository-url=$(params.repository-url)"
        echo "revision=$(params.revision)"
        echo "ref=$(params.ref)"
        echo "event-type=$(params.event-type)"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: url
    - name: rev
  workspaces:
    - name: output
  steps:
    - name: echo-clone
      image: 'registry.access.redhat.com/ubi9/ubi-minimal:9.6'
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        echo ">>> [PARAMS]"
        echo "URL=$(params.url)"
        echo "REV=$(params.rev)"
        echo "TARGET=$(workspaces.output.path)"
        echo ">>> Installing Git..."
        microdnf install -y git && microdnf clean all
        echo ">>> Cloning Repo into $TARGET ..."
        rm -rf .
        git clone --branch "$(params.rev)" "$(params.url)" .

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  params:
    - name: repository-url
  workspaces:
    - name: output
  steps:
    - name: run-lint
      image: 'registry.access.redhat.com/ubi9/python-311:9.6'
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        echo ">>> [PARAMS]"
        echo "Repo=$(params.repository-url)"
        echo "Workspace=$(workspaces.output.path)"
        echo ">>> Installing requirements.txt..."
        pip3 install -r requirements.txt
        echo ">>> Installing Make..."
        microdnf install -y make && microdnf clean all
        echo ">>> Running Lint..."
        make lint

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: output
  steps:
    - name: echo-deploy
      image: 'registry.access.redhat.com/ubi9/ubi-minimal:9.6'
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        echo ">>> [DEPLOY DUMMY] running for push to refs/heads/main"
        echo ">>> Installing Make..."
        microdnf install -y make && microdnf clean all
        echo ">>> Running Deploy..."
        make deploy
