apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-params-task
spec:
  params:
    - name: repository-url
    - name: revision
    - name: ref
    - name: event-type
  steps:
    - name: echo-params
      image: alpine:3.19
      script: |
        #!/bin/sh
        echo ">>> [SHOW PARAMS]"
        echo "repository-url=$(params.repository-url)"
        echo "revision=$(params.revision)"
        echo "ref=$(params.ref)"
        echo "event-type=$(params.event-type)"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: url
    - name: rev
  workspaces:
    - name: output
  steps:
    - name: echo-clone
      image: alpine:3.19
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        echo ">>> [PARAMS]"
        echo "URL=$(params.url)"
        echo "REV=$(params.rev)"
        echo "TARGET=$(workspaces.output.path)"
        echo ">>> Installing Git..."
        yum install -y git
        echo ">>> Cloning Repo..."
        git clone --branch "$revision" "$repository_url"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  params:
    - name: repository-url
  workspaces:
    - name: source
  steps:
    - name: run-lint
      image: python:3.10
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        echo ">>> [PARAMS]"
        echo "Repo=$(params.repository-url)"
        echo "Workspace=$(workspaces.output.path)"
        echo ">>> Installing requirements.txt..."
        pip3 install -r requirements.txt
        echo ">>> Installing Make..."
        yum install -y make
        echo ">>> Running Lint..."
        make lint

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: source
  steps:
    - name: echo-deploy
      image: alpine:3.19
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        echo ">>> [DEPLOY DUMMY] running for push to refs/heads/main"
        echo ">>> Installing Make..."
        yum install -y make
        echo ">>> Running Deploy..."
        make deploy
