apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  params:
    - name: repository
    - name: revision
      default: main
  workspaces:
    - name: source
  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        echo "Cleaning workspace..."
        rm -rf /workspace/source/*
        echo "Cloning $(params.repository) branch $(params.revision)"
        git clone -b $(params.revision) $(params.repository) /workspace/source
        pwd
    - name: run-pylint
      image: python:3.10
      workingDir: $(workspaces.source.path)
      script: |
        # Install pylint
        pwd
        find testcases/
        pip install pylint
        # Run pylint only on the testcases folder
        pylint $(find testcases/ -type f -name "*.py") || true
