apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  workspaces:
    - name: source
  steps:
    - name: run-pylint
      image: python:3.10
      workingDir: $(workspaces.source.path)
      script: |
        # Install pylint
        pip install pylint
        # Run pylint only on the testcases folder
        pylint python/ || true
