apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-dummy
spec:
  params:
    - name: repository-url
    - name: revision
  steps:
    - name: echo
      image: alpine:3.18
      script: |
        echo "[GIT CLONE] Would clone $(params.repository-url) revision $(params.revision)"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-dummy
spec:
  steps:
    - name: echo
      image: alpine:3.18
      script: |
        echo "[LINT] Would run pylint inside testcases/ folder"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-dummy
spec:
  steps:
    - name: echo
      image: alpine:3.18
      script: |
        echo "[DEPLOY] Would deploy application on push to main"
