---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: url
      type: string
    - name: rev
      type: string
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        echo "Repository URL: '$(params.url)'"
        echo "Requested revision: '$(params.rev)'"
        if [ -z "$(params.url)" ]; then exit 1; fi
        REV="$(params.rev)"
        case "$REV" in
          refs/heads/*) REV="${REV#refs/heads/}" ;;
          ""|" " ) REV="main" ;;
        esac
        rm -rf source || true
        git clone --depth 1 --branch "$REV" "$(params.url)" source || {
          git clone "$(params.url)" source
          cd source
          git checkout "$REV" || true
          exit 0
        }
        cd source
        git status
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  workspaces:
    - name: source
  steps:
    - name: run-pylint
      image: python:3.11
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/bin/sh
        set -e
        pip install pylint
        # Run pylint only on the testcases folder
        pylint $(find testcases/ -type f -name "*.py") || true
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: source
  steps:
    - name: echo-deploy
      image: alpine:3.19
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/bin/sh
        set -e
        echo "Deploy to main (dummy)"
