---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: url
      type: string
    - name: rev
      type: string
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        echo "Clone (dummy)" || true
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  workspaces:
    - name: source
  steps:
    - name: run-pylint
      image: python:3.11
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/bin/sh
        set -e
        echo "Lint (dummy)" || true
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: source
  steps:
    - name: echo-deploy
      image: alpine:3.19
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/bin/sh
        set -e
        echo "Deploy to main (dummy)" || true
