---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  params:
    - name: repository
      description: Git repository URL
    - name: branch
      description: Branch to checkout
  workspaces:
    - name: shared-workspace
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        #!/bin/sh
        echo "Cleaning workspace..."
        rm -rf /workspace/source/*
        echo "Cloning $(params.repository) branch $(params.revision)"
        git clone -b $(params.revision) $(params.repository) /workspace/source

    - name: run-lint
      image: python:3.9
      workingDir: $(workspaces.shared-workspace.path)/repo
      script: |
        #!/bin/sh
        set -e
        pip install pylint
        # Run pylint only on the testcases folder
        pylint $(find testcases/ -type f -name "*.py") || true

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  params:
    - name: repository
      description: Git repository URL
    - name: branch
      description: Branch to checkout
  workspaces:
    - name: shared-workspace
  steps:
    - name: echo-deploy
      image: alpine
      script: |
        #!/bin/sh
        echo "This is a deploy step (branch: $(params.branch))"
